name: assignment2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.5.0
  flutter_screenutil: ^5.8.4
  curved_navigation_bar: ^1.0.3
  swipeable_card_stack:
  http: ^1.1.0
  get: ^4.6.5
  shared_preferences: ^2.2.0
  palette_generator: ^0.3.3+2
  otp_text_field: ^1.1.3
  intl: ^0.18.1
  image_picker: ^1.0.2
  flutter_glow: ^0.3.0
  awesome_dialog: ^3.1.0
  flutter_swiper_view: ^1.1.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/png/
    - assets/images/
    - assets/images/list_dog/

